---
driver:
  name: vagrant

provisioner:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-10.04
  run_list:
    - recipe[apt]
- name: ubuntu-12.04
  run_list:
    - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: debian-6.0.10
  run_list:
    - recipe[apt]
- name: debian-7.6
  run_list:
    - recipe[apt]
- name: centos-5.9
- name: centos-6.5

suites:
- name: default
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    mysql:
      server_root_password: vagrant
      server_debian_password: vagrant_debian
      server_repl_password: vagrant_repl
    postfixadmin:
      database:
        password: postfix_pass
      setup_password: admin
      setup_password_salt: salt
- name: without-webserver
  run_list:
  - recipe[postfixadmin_test]
  attributes:
    mysql:
      server_root_password: vagrant
      server_debian_password: vagrant_debian
      server_repl_password: vagrant_repl
    postfixadmin:
      database:
        password: postfix_pass
      setup_password: admin
      setup_password_salt: salt
      web_server: false
- name: map_files
  run_list:
  - recipe[postfix-full]
  - recipe[postfixadmin_test::map_files]
  attributes:
    postfixadmin:
      database:
        password: postfix_pass
      setup_password: admin
      setup_password_salt: salt
- name: lwrp
  run_list:
  - recipe[postfixadmin_test::lwrp]
  attributes: { }
- name: lwrp_ssl
  run_list:
  - recipe[postfixadmin_test::lwrp]
  attributes:
    postfixadmin:
      ssl: true
